/*Copyright 2020-2021 T-Head Semiconductor Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
`define NOISA










`timescale 1ns/100ps
`define CLK_PERIOD          10
`define TCLK_PERIOD         40
`define MAX_RUN_TIME        700000000

`define SOC_TOP             top.x_soc
`define RTL_MEM             top.x_soc.x_axi_slave128.x_f_spsram_524288x128_L
`define RTL_MEM2            top.x_soc.x_axi_slave128.x_f_spsram_524288x128_H



`define CPU_TOP             top.x_soc.x_cpu_sub_system_axi.x_c906_wrapper.x_cpu_top
`define tb_retire0          `CPU_TOP.core0_pad_retire
`define retire0_pc          `CPU_TOP.core0_pad_retire_pc[39:0]
`define CPU_CLK             `CPU_TOP.pll_core_cpuclk
`define CPU_RST             `CPU_TOP.pad_cpu_rst_b
`define LSU_TOP             `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_lsu_top
`define LSU_STB             `LSU_TOP.x_aq_lsu_stb



module top(
  input wire clk
);
// clk is a top-level port
reg jclk;
reg rst_b;
reg jrst_b;
reg jtap_en;
wire jtg_tms;
wire jtg_tdi;
wire jtg_tdo;
wire  pad_yy_gate_clk_en_b;

static integer FILE;

wire uart0_sin;
wire [7:0]b_pad_gpio_porta;

assign pad_yy_gate_clk_en_b = 1'b1;


// clk is generated by sim_main; this initial block intentionally removed for Verilator

initial 
begin 
  jclk = 0;
  forever begin
    #(`TCLK_PERIOD/2) jclk = ~jclk;
  end
end


initial
begin
  rst_b = 1;
  #100;
  rst_b = 0;
  #100;
  rst_b = 1;
end

initial
begin
  jrst_b = 1;
  #400;
  jrst_b = 0;
  #400;
  jrst_b = 1;
end

integer i;
  bit [31:0] mem_inst_temp [65536];
  bit [31:0] mem_data_temp [65536];
  integer j;
  initial
  begin
    $display("\t********* Init Program *********");
    $display("\t********* Wipe memory to 0 *********");
    for(i=0; i < 32'h16384; i=i+1)
    begin
      `RTL_MEM.ram0.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram1.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram2.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram3.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram4.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram5.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram6.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram7.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram8.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram9.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram10.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram11.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram12.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram13.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram14.mem[i][7:0] = 8'h0;
      `RTL_MEM.ram15.mem[i][7:0] = 8'h0;
    end
  
    $display("\t********* Read program *********");
    $readmemh("inst.pat", mem_inst_temp);
    $readmemh("data.pat", mem_data_temp);
  
    $display("\t********* Load program to memory *********");
    i=0;
    for(j=0;i<32'h4000;i=j/4)
    begin
      `RTL_MEM.ram0.mem[i][7:0] = mem_inst_temp[j][31:24];
      `RTL_MEM.ram1.mem[i][7:0] = mem_inst_temp[j][23:16];
      `RTL_MEM.ram2.mem[i][7:0] = mem_inst_temp[j][15: 8];
      `RTL_MEM.ram3.mem[i][7:0] = mem_inst_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram4.mem[i][7:0] = mem_inst_temp[j][31:24];
      `RTL_MEM.ram5.mem[i][7:0] = mem_inst_temp[j][23:16];
      `RTL_MEM.ram6.mem[i][7:0] = mem_inst_temp[j][15: 8];
      `RTL_MEM.ram7.mem[i][7:0] = mem_inst_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram8.mem[i][7:0] = mem_inst_temp[j][31:24];
      `RTL_MEM.ram9.mem[i][7:0] = mem_inst_temp[j][23:16];
      `RTL_MEM.ram10.mem[i][7:0] = mem_inst_temp[j][15: 8];
      `RTL_MEM.ram11.mem[i][7:0] = mem_inst_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram12.mem[i][7:0] = mem_inst_temp[j][31:24];
      `RTL_MEM.ram13.mem[i][7:0] = mem_inst_temp[j][23:16];
      `RTL_MEM.ram14.mem[i][7:0] = mem_inst_temp[j][15: 8];
      `RTL_MEM.ram15.mem[i][7:0] = mem_inst_temp[j][ 7: 0];
      j = j+1;
    end
    i=0;
    for(j=0;i<32'h4000;i=j/4)
    begin
      `RTL_MEM.ram0.mem[i+32'h4000][7:0]  = mem_data_temp[j][31:24];
      `RTL_MEM.ram1.mem[i+32'h4000][7:0]  = mem_data_temp[j][23:16];
      `RTL_MEM.ram2.mem[i+32'h4000][7:0]  = mem_data_temp[j][15: 8];
      `RTL_MEM.ram3.mem[i+32'h4000][7:0]  = mem_data_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram4.mem[i+32'h4000][7:0]  = mem_data_temp[j][31:24];
      `RTL_MEM.ram5.mem[i+32'h4000][7:0]  = mem_data_temp[j][23:16];
      `RTL_MEM.ram6.mem[i+32'h4000][7:0]  = mem_data_temp[j][15: 8];
      `RTL_MEM.ram7.mem[i+32'h4000][7:0]  = mem_data_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram8.mem[i+32'h4000][7:0]   = mem_data_temp[j][31:24];
      `RTL_MEM.ram9.mem[i+32'h4000][7:0]   = mem_data_temp[j][23:16];
      `RTL_MEM.ram10.mem[i+32'h4000][7:0]  = mem_data_temp[j][15: 8];
      `RTL_MEM.ram11.mem[i+32'h4000][7:0]  = mem_data_temp[j][ 7: 0];
      j = j+1;
      `RTL_MEM.ram12.mem[i+32'h4000][7:0]  = mem_data_temp[j][31:24];
      `RTL_MEM.ram13.mem[i+32'h4000][7:0]  = mem_data_temp[j][23:16];
      `RTL_MEM.ram14.mem[i+32'h4000][7:0]  = mem_data_temp[j][15: 8];
      `RTL_MEM.ram15.mem[i+32'h4000][7:0]  = mem_data_temp[j][ 7: 0];
      j = j+1;
    end
  end









initial
begin
#`MAX_RUN_TIME;
  $display("**********************************************");
  $display("*   meeting max simulation time, stop!       *");
  $display("**********************************************");
  FILE = $fopen("run_case.report","a");
  $fwrite(FILE,"TEST FAIL");   
$finish;
end

reg [31:0] retire_inst_in_period;
reg [31:0] cycle_count;

`define LAST_CYCLE 50000
always @(posedge clk or negedge rst_b)
begin
  if(!rst_b)
    cycle_count[31:0] <= 32'b1;
  else 
    cycle_count[31:0] <= cycle_count[31:0] + 1'b1;
end


always @(posedge clk or negedge rst_b)
begin
  if(!rst_b) //reset to zero
    retire_inst_in_period[31:0] <= 32'b0;
  else if( (cycle_count[31:0] % `LAST_CYCLE) == 0)//check and reset retire_inst_in_period every 50000 cycles
  begin
    if(retire_inst_in_period[31:0] == 0)begin
      $display("*************************************************************");
      $display("* Error: There is no instructions retired in the last %d cycles! *", `LAST_CYCLE);
      $display("*              Simulation Fail and Finished!                *");
      $display("*************************************************************");
      #10;
      FILE = $fopen("run_case.report","a");
      $fwrite(FILE,"TEST FAIL");   

      $finish;
    end
    retire_inst_in_period[31:0] <= 32'b0;
  end
  else if(`tb_retire0)
    retire_inst_in_period[31:0] <= retire_inst_in_period[31:0] + 1'b1;
end



reg [39:0] cpu_awaddr;
reg [3:0]  cpu_awlen;
reg [15:0] cpu_wstrb;
reg        cpu_wvalid;
reg [127:0] cpu_wdata;
reg [63:0] value0;
reg [63:0] value1;

`ifdef CX_TRACE
integer cx_trace_file;
reg [4095:0] cx_trace_path;
reg cx_trace_started;
reg [31:0] cx_trace_last_commit_cycle;
reg [39:0] cx_trace_last_commit_pc;
reg cx_trace_last_commit_vld;
reg [39:0] cx_trace_amo_pc [0:3];
reg        cx_trace_amo_pc_vld [0:3];
reg [39:0] cx_trace_store_pc [0:3];
reg        cx_trace_store_pc_vld [0:3];
reg [7:0]  cx_trace_store_bytes_vld [0:3];
reg [1:0]  cx_trace_store_size [0:3];
integer    cx_trace_slot;

function [39:0] cx_trace_store_create_pc;
  begin
    if(`tb_retire0)
      cx_trace_store_create_pc = `retire0_pc;
    else
      cx_trace_store_create_pc = {24'b0, `LSU_TOP.ag_dc_inst_pc[15:0]};
  end
endfunction

function [7:0] cx_trace_store_mask_from_size;
  input [1:0] raw_size;
  begin
    case(raw_size)
      2'b00: cx_trace_store_mask_from_size = 8'h01;
      2'b01: cx_trace_store_mask_from_size = 8'h03;
      2'b10: cx_trace_store_mask_from_size = 8'h0f;
      default: cx_trace_store_mask_from_size = 8'hff;
    endcase
  end
endfunction

function [7:0] cx_trace_fetch_mem_byte;
  input [39:0] raw_addr;
  integer line_idx;
  begin
    line_idx = raw_addr[17:4];
    case (raw_addr[3:0])
      4'h0: cx_trace_fetch_mem_byte = `RTL_MEM.ram0.mem[line_idx][7:0];
      4'h1: cx_trace_fetch_mem_byte = `RTL_MEM.ram1.mem[line_idx][7:0];
      4'h2: cx_trace_fetch_mem_byte = `RTL_MEM.ram2.mem[line_idx][7:0];
      4'h3: cx_trace_fetch_mem_byte = `RTL_MEM.ram3.mem[line_idx][7:0];
      4'h4: cx_trace_fetch_mem_byte = `RTL_MEM.ram4.mem[line_idx][7:0];
      4'h5: cx_trace_fetch_mem_byte = `RTL_MEM.ram5.mem[line_idx][7:0];
      4'h6: cx_trace_fetch_mem_byte = `RTL_MEM.ram6.mem[line_idx][7:0];
      4'h7: cx_trace_fetch_mem_byte = `RTL_MEM.ram7.mem[line_idx][7:0];
      4'h8: cx_trace_fetch_mem_byte = `RTL_MEM.ram8.mem[line_idx][7:0];
      4'h9: cx_trace_fetch_mem_byte = `RTL_MEM.ram9.mem[line_idx][7:0];
      4'ha: cx_trace_fetch_mem_byte = `RTL_MEM.ram10.mem[line_idx][7:0];
      4'hb: cx_trace_fetch_mem_byte = `RTL_MEM.ram11.mem[line_idx][7:0];
      4'hc: cx_trace_fetch_mem_byte = `RTL_MEM.ram12.mem[line_idx][7:0];
      4'hd: cx_trace_fetch_mem_byte = `RTL_MEM.ram13.mem[line_idx][7:0];
      4'he: cx_trace_fetch_mem_byte = `RTL_MEM.ram14.mem[line_idx][7:0];
      default: cx_trace_fetch_mem_byte = `RTL_MEM.ram15.mem[line_idx][7:0];
    endcase
  end
endfunction

function [31:0] cx_trace_fetch_inst32;
  input [39:0] raw_pc;
  begin
    cx_trace_fetch_inst32 = {cx_trace_fetch_mem_byte(raw_pc + 40'd3),
                             cx_trace_fetch_mem_byte(raw_pc + 40'd2),
                             cx_trace_fetch_mem_byte(raw_pc + 40'd1),
                             cx_trace_fetch_mem_byte(raw_pc)};
  end
endfunction

function [7:0] cx_trace_mask_for_width;
  input [39:0] raw_addr;
  input [3:0] width_bytes;
  begin
    case (width_bytes)
      4'd1: cx_trace_mask_for_width = 8'h01 << raw_addr[2:0];
      4'd2: cx_trace_mask_for_width = 8'h03 << raw_addr[2:0];
      4'd4: cx_trace_mask_for_width = 8'h0f << raw_addr[2:0];
      4'd8: cx_trace_mask_for_width = 8'hff;
      default: cx_trace_mask_for_width = 8'h00;
    endcase
  end
endfunction

function [7:0] cx_trace_decode_store_bytes_vld;
  input [39:0] raw_pc;
  input [39:0] raw_addr;
  input [7:0] fallback_bytes_vld;
  reg [31:0] inst32;
  begin
    inst32 = cx_trace_fetch_inst32(raw_pc);
    case (inst32[6:0])
      7'b0100011,
      7'b0100111: begin
        case (inst32[14:12])
          3'b000: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd1);
          3'b001: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd2);
          3'b010: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd4);
          3'b011: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd8);
          default: cx_trace_decode_store_bytes_vld = fallback_bytes_vld;
        endcase
      end
      7'b0101111: begin
        case (inst32[14:12])
          3'b010: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd4);
          3'b011: cx_trace_decode_store_bytes_vld = cx_trace_mask_for_width(raw_addr, 4'd8);
          default: cx_trace_decode_store_bytes_vld = fallback_bytes_vld;
        endcase
      end
      default: cx_trace_decode_store_bytes_vld = fallback_bytes_vld;
    endcase
  end
endfunction

function [15:0] cx_trace_expand_store_bytes_vld;
  input [39:0] raw_addr;
  input [7:0] raw_bytes_vld;
  begin
    cx_trace_expand_store_bytes_vld = raw_addr[3]
      ? {raw_bytes_vld, 8'b0}
      : {8'b0, raw_bytes_vld};
  end
endfunction

function [63:0] cx_trace_pack_store_data;
  input [63:0] lane_data;
  input [7:0] raw_bytes_vld;
  integer src;
  integer dst;
  reg [63:0] packed_data;
  reg [63:0] byte_value;
  begin
    packed_data = 64'b0;
    dst = 0;
    for (src = 0; src < 8; src = src + 1) begin
      if (raw_bytes_vld[src]) begin
        byte_value = (lane_data >> (src * 8)) & 64'hff;
        packed_data = packed_data | (byte_value << (dst * 8));
        dst = dst + 1;
      end
    end
    cx_trace_pack_store_data = packed_data;
  end
endfunction

function [127:0] cx_trace_expand_store_data128;
  input [39:0] raw_addr;
  input [7:0] raw_bytes_vld;
  input [63:0] lane_data;
  integer src;
  integer dst;
  reg [127:0] expanded_data;
  reg [127:0] byte_value;
  reg [127:0] lane_data_ext;
  begin
    expanded_data = 128'b0;
    lane_data_ext = {64'b0, lane_data};
    for (src = 0; src < 8; src = src + 1) begin
      if (raw_bytes_vld[src]) begin
        dst = raw_addr[3] ? (src + 8) : src;
        byte_value = (lane_data_ext >> (src * 8)) & 128'hff;
        expanded_data = expanded_data | (byte_value << (dst * 8));
      end
    end
    cx_trace_expand_store_data128 = expanded_data;
  end
endfunction

task cx_trace_store_raw8;
  input [31:0] raw_cycle;
  input [39:0] raw_addr;
  input [7:0] raw_bytes_vld;
  input [63:0] lane_data;
  reg [7:0] trace_bytes_vld;
  begin
    if(raw_bytes_vld != 8'b0 &&
       raw_addr[31:0] >= 32'h00040000 &&
       raw_addr[31:0] < 32'h00100000) begin
      if(cx_trace_last_commit_vld && raw_cycle == cx_trace_last_commit_cycle) begin
        trace_bytes_vld = cx_trace_decode_store_bytes_vld(cx_trace_last_commit_pc,
                                                          raw_addr,
                                                          raw_bytes_vld);
        $fwrite(cx_trace_file,
                "store cycle=%0d hart=0 pc=0x%010x addr=0x%010x mask=0x%04x data=0x%032x\n",
                raw_cycle,
                cx_trace_last_commit_pc,
                raw_addr,
                cx_trace_expand_store_bytes_vld(raw_addr, trace_bytes_vld),
                cx_trace_expand_store_data128(raw_addr, trace_bytes_vld, lane_data));
      end
      else if(`tb_retire0) begin
        trace_bytes_vld = cx_trace_decode_store_bytes_vld(`retire0_pc,
                                                          raw_addr,
                                                          raw_bytes_vld);
        $fwrite(cx_trace_file,
                "store cycle=%0d hart=0 pc=0x%010x addr=0x%010x mask=0x%04x data=0x%032x\n",
                raw_cycle,
                `retire0_pc,
                raw_addr,
                cx_trace_expand_store_bytes_vld(raw_addr, trace_bytes_vld),
                cx_trace_expand_store_data128(raw_addr, trace_bytes_vld, lane_data));
      end
      else begin
        $fwrite(cx_trace_file,
                "store_raw cycle=%0d hart=0 raw_addr=0x%010x raw_bytes_vld=0x%04x raw_data=0x%016x addr_cycle=%0d\n",
                raw_cycle,
                raw_addr,
                cx_trace_expand_store_bytes_vld(raw_addr, raw_bytes_vld),
                cx_trace_pack_store_data(lane_data, raw_bytes_vld),
                raw_cycle);
      end
    end
  end
endtask

task cx_trace_store_with_pc8;
  input [31:0] raw_cycle;
  input [39:0] raw_pc;
  input [39:0] raw_addr;
  input [7:0] raw_bytes_vld;
  input [63:0] lane_data;
  reg [7:0] trace_bytes_vld;
  begin
    if(raw_pc != 40'b0 &&
       raw_bytes_vld != 8'b0 &&
       raw_addr[31:0] >= 32'h00040000 &&
       raw_addr[31:0] < 32'h00100000) begin
      trace_bytes_vld = cx_trace_decode_store_bytes_vld(raw_pc,
                                                        raw_addr,
                                                        raw_bytes_vld);
      $fwrite(cx_trace_file,
              "store cycle=%0d hart=0 pc=0x%010x addr=0x%010x mask=0x%04x data=0x%032x\n",
              raw_cycle,
              raw_pc,
              raw_addr,
              cx_trace_expand_store_bytes_vld(raw_addr, trace_bytes_vld),
              cx_trace_expand_store_data128(raw_addr, trace_bytes_vld, lane_data));
    end
  end
endtask

initial
begin
  if(!$value$plusargs("cx_trace=%s", cx_trace_path)) begin
    cx_trace_path = "openc906_trace_hart_00000000.log";
  end
  cx_trace_file = $fopen(cx_trace_path, "w");
  cx_trace_started = 1'b0;
  cx_trace_last_commit_cycle = 32'b0;
  cx_trace_last_commit_pc = 40'b0;
  cx_trace_last_commit_vld = 1'b0;
  for (cx_trace_slot = 0; cx_trace_slot < 4; cx_trace_slot = cx_trace_slot + 1) begin
    cx_trace_amo_pc[cx_trace_slot] = 40'b0;
    cx_trace_amo_pc_vld[cx_trace_slot] = 1'b0;
    cx_trace_store_pc[cx_trace_slot] = 40'b0;
    cx_trace_store_pc_vld[cx_trace_slot] = 1'b0;
    cx_trace_store_bytes_vld[cx_trace_slot] = 8'b0;
    cx_trace_store_size[cx_trace_slot] = 2'b0;
  end
end

always @(posedge clk or negedge rst_b)
begin
  if(!rst_b) begin
    for (cx_trace_slot = 0; cx_trace_slot < 4; cx_trace_slot = cx_trace_slot + 1) begin
      cx_trace_amo_pc[cx_trace_slot] <= 40'b0;
      cx_trace_amo_pc_vld[cx_trace_slot] <= 1'b0;
      cx_trace_store_pc[cx_trace_slot] <= 40'b0;
      cx_trace_store_pc_vld[cx_trace_slot] <= 1'b0;
      cx_trace_store_bytes_vld[cx_trace_slot] <= 8'b0;
      cx_trace_store_size[cx_trace_slot] <= 2'b0;
    end
  end
  else begin
    if(`LSU_STB.stb_create_en_gate[0] &&
       !`LSU_STB.stb_create_dca_inst &&
       !`LSU_STB.stb_create_amo_inst &&
       `LSU_STB.stb_create_src2_depd) begin
      cx_trace_store_pc[0] <= cx_trace_store_create_pc();
      cx_trace_store_pc_vld[0] <= 1'b1;
      cx_trace_store_bytes_vld[0] <= `LSU_STB.stb_create_bytes_vld[7:0];
      cx_trace_store_size[0] <= `LSU_TOP.ag_dc_func[3:2];
    end
    if(`LSU_STB.stb_create_en_gate[1] &&
       !`LSU_STB.stb_create_dca_inst &&
       !`LSU_STB.stb_create_amo_inst &&
       `LSU_STB.stb_create_src2_depd) begin
      cx_trace_store_pc[1] <= cx_trace_store_create_pc();
      cx_trace_store_pc_vld[1] <= 1'b1;
      cx_trace_store_bytes_vld[1] <= `LSU_STB.stb_create_bytes_vld[7:0];
      cx_trace_store_size[1] <= `LSU_TOP.ag_dc_func[3:2];
    end
    if(`LSU_STB.stb_create_en_gate[2] &&
       !`LSU_STB.stb_create_dca_inst &&
       !`LSU_STB.stb_create_amo_inst &&
       `LSU_STB.stb_create_src2_depd) begin
      cx_trace_store_pc[2] <= cx_trace_store_create_pc();
      cx_trace_store_pc_vld[2] <= 1'b1;
      cx_trace_store_bytes_vld[2] <= `LSU_STB.stb_create_bytes_vld[7:0];
      cx_trace_store_size[2] <= `LSU_TOP.ag_dc_func[3:2];
    end
    if(`LSU_STB.stb_create_en_gate[3] &&
       !`LSU_STB.stb_create_dca_inst &&
       !`LSU_STB.stb_create_amo_inst &&
       `LSU_STB.stb_create_src2_depd) begin
      cx_trace_store_pc[3] <= cx_trace_store_create_pc();
      cx_trace_store_pc_vld[3] <= 1'b1;
      cx_trace_store_bytes_vld[3] <= `LSU_STB.stb_create_bytes_vld[7:0];
      cx_trace_store_size[3] <= `LSU_TOP.ag_dc_func[3:2];
    end
    if(`LSU_STB.stb_create_en_gate[0] && `LSU_STB.stb_create_amo_inst) begin
      cx_trace_amo_pc[0] <= {24'b0, `LSU_TOP.ag_dc_inst_pc[15:0]};
      cx_trace_amo_pc_vld[0] <= 1'b1;
    end
    if(`LSU_STB.stb_create_en_gate[1] && `LSU_STB.stb_create_amo_inst) begin
      cx_trace_amo_pc[1] <= {24'b0, `LSU_TOP.ag_dc_inst_pc[15:0]};
      cx_trace_amo_pc_vld[1] <= 1'b1;
    end
    if(`LSU_STB.stb_create_en_gate[2] && `LSU_STB.stb_create_amo_inst) begin
      cx_trace_amo_pc[2] <= {24'b0, `LSU_TOP.ag_dc_inst_pc[15:0]};
      cx_trace_amo_pc_vld[2] <= 1'b1;
    end
    if(`LSU_STB.stb_create_en_gate[3] && `LSU_STB.stb_create_amo_inst) begin
      cx_trace_amo_pc[3] <= {24'b0, `LSU_TOP.ag_dc_inst_pc[15:0]};
      cx_trace_amo_pc_vld[3] <= 1'b1;
    end
    if(`LSU_STB.x_aq_lsu_stb_entry_0.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_vld)) begin
      cx_trace_amo_pc_vld[0] <= 1'b0;
    end
    if(!`LSU_STB.x_aq_lsu_stb_entry_0.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_vld)) begin
      cx_trace_store_pc_vld[0] <= 1'b0;
      cx_trace_store_bytes_vld[0] <= 8'b0;
      cx_trace_store_size[0] <= 2'b0;
    end
    if(`LSU_STB.x_aq_lsu_stb_entry_1.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_vld)) begin
      cx_trace_amo_pc_vld[1] <= 1'b0;
    end
    if(!`LSU_STB.x_aq_lsu_stb_entry_1.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_vld)) begin
      cx_trace_store_pc_vld[1] <= 1'b0;
      cx_trace_store_bytes_vld[1] <= 8'b0;
      cx_trace_store_size[1] <= 2'b0;
    end
    if(`LSU_STB.x_aq_lsu_stb_entry_2.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_vld)) begin
      cx_trace_amo_pc_vld[2] <= 1'b0;
    end
    if(!`LSU_STB.x_aq_lsu_stb_entry_2.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_vld)) begin
      cx_trace_store_pc_vld[2] <= 1'b0;
      cx_trace_store_bytes_vld[2] <= 8'b0;
      cx_trace_store_size[2] <= 2'b0;
    end
    if(`LSU_STB.x_aq_lsu_stb_entry_3.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_vld)) begin
      cx_trace_amo_pc_vld[3] <= 1'b0;
    end
    if(!`LSU_STB.x_aq_lsu_stb_entry_3.stb_entry_amo_inst &&
       (`LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_vld ||
        `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_vld)) begin
      cx_trace_store_pc_vld[3] <= 1'b0;
      cx_trace_store_bytes_vld[3] <= 8'b0;
      cx_trace_store_size[3] <= 2'b0;
    end
  end
end

always @(posedge clk)
begin
  if(cx_trace_file != 0) begin
    if(`tb_retire0) begin
      cx_trace_last_commit_cycle = cycle_count[31:0];
      cx_trace_last_commit_pc = `retire0_pc;
      cx_trace_last_commit_vld = 1'b1;
      $fwrite(cx_trace_file, "commit cycle=%0d hart=0 pc=0x%010x", cycle_count[31:0], `retire0_pc);
      if(`CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_dp.dp_retire_ex2_inst_expt) begin
        $fwrite(cx_trace_file, " exc_cause=%0d", `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_dp.dp_retire_ex2_vec[4:0]);
      end
      $fwrite(cx_trace_file, "\n");
      cx_trace_started <= 1'b1;
    end
    if(cx_trace_started || `tb_retire0) begin
      if(`CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb0_vld &&
         (`CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb0_reg[4:0] != 5'd0)) begin
        $fwrite(cx_trace_file, "regwrite cycle=%0d hart=0 rd=x%0d rd_val=0x%016x\n",
                cycle_count[31:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb0_reg[4:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb0_data[63:0]);
      end
      if(`CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb1_vld &&
         (`CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb1_reg[4:0] != 5'd0)) begin
        $fwrite(cx_trace_file, "regwrite cycle=%0d hart=0 rd=x%0d rd_val=0x%016x\n",
                cycle_count[31:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb1_reg[4:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb1_data[63:0]);
      end
      if(`CPU_TOP.x_aq_top_0.x_aq_core.vpu_vidu_fp_wb_vld) begin
        $fwrite(cx_trace_file, "fpwrite cycle=%0d hart=0 rd=f%0d rd_val=0x%016x\n",
                cycle_count[31:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.vpu_vidu_fp_wb_reg[4:0],
                `CPU_TOP.x_aq_top_0.x_aq_core.vpu_vidu_fp_wb_data[63:0]);
      end
      if(`LSU_STB.stb_create_en_gate[0] &&
         !`LSU_STB.stb_create_dca_inst &&
         !`LSU_STB.stb_create_amo_inst &&
         !`LSU_STB.stb_create_src2_depd) begin
        cx_trace_store_with_pc8(cycle_count[31:0],
                                cx_trace_store_create_pc(),
                                `LSU_STB.stb_create_pa[39:0],
                                `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.stb_create_data[63:0]);
      end
      if(`LSU_STB.stb_create_en_gate[1] &&
         !`LSU_STB.stb_create_dca_inst &&
         !`LSU_STB.stb_create_amo_inst &&
         !`LSU_STB.stb_create_src2_depd) begin
        cx_trace_store_with_pc8(cycle_count[31:0],
                                cx_trace_store_create_pc(),
                                `LSU_STB.stb_create_pa[39:0],
                                `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.stb_create_data[63:0]);
      end
      if(`LSU_STB.stb_create_en_gate[2] &&
         !`LSU_STB.stb_create_dca_inst &&
         !`LSU_STB.stb_create_amo_inst &&
         !`LSU_STB.stb_create_src2_depd) begin
        cx_trace_store_with_pc8(cycle_count[31:0],
                                cx_trace_store_create_pc(),
                                `LSU_STB.stb_create_pa[39:0],
                                `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.stb_create_data[63:0]);
      end
      if(`LSU_STB.stb_create_en_gate[3] &&
         !`LSU_STB.stb_create_dca_inst &&
         !`LSU_STB.stb_create_amo_inst &&
         !`LSU_STB.stb_create_src2_depd) begin
        cx_trace_store_with_pc8(cycle_count[31:0],
                                cx_trace_store_create_pc(),
                                `LSU_STB.stb_create_pa[39:0],
                                `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.stb_create_data[63:0]);
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_0.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[0]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[0],
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  `LSU_STB.stb_entry0_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[0] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[0]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[0],
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  cx_trace_store_bytes_vld[0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_data[63:0]);
        end
        else if(!`LSU_STB.x_aq_lsu_stb_entry_0.stb_entry_amo_inst) begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry0_pa[39:0],
                                    `LSU_STB.stb_entry0_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry0_pa[39:0],
                                `LSU_STB.stb_entry0_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_1.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[1]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[1],
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  `LSU_STB.stb_entry1_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[1] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[1]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[1],
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  cx_trace_store_bytes_vld[1],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_data[63:0]);
        end
        else if(!`LSU_STB.x_aq_lsu_stb_entry_1.stb_entry_amo_inst) begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry1_pa[39:0],
                                    `LSU_STB.stb_entry1_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry1_pa[39:0],
                                `LSU_STB.stb_entry1_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_2.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[2]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[2],
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  `LSU_STB.stb_entry2_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[2] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[2]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[2],
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  cx_trace_store_bytes_vld[2],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_data[63:0]);
        end
        else if(!`LSU_STB.x_aq_lsu_stb_entry_2.stb_entry_amo_inst) begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry2_pa[39:0],
                                    `LSU_STB.stb_entry2_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry2_pa[39:0],
                                `LSU_STB.stb_entry2_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_3.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[3]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[3],
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  `LSU_STB.stb_entry3_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[3] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[3]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[3],
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  cx_trace_store_bytes_vld[3],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_data[63:0]);
        end
        else if(!`LSU_STB.x_aq_lsu_stb_entry_3.stb_entry_amo_inst) begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry3_pa[39:0],
                                    `LSU_STB.stb_entry3_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry3_pa[39:0],
                                `LSU_STB.stb_entry3_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_0.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[0]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[0],
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  `LSU_STB.stb_entry0_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[0] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[0]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[0],
                                  `LSU_STB.stb_entry0_pa[39:0],
                                  cx_trace_store_bytes_vld[0],
                                  `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_data[63:0]);
        end
        else begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry0_pa[39:0],
                                    `LSU_STB.stb_entry0_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry0_pa[39:0],
                                `LSU_STB.stb_entry0_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_1.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[1]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[1],
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  `LSU_STB.stb_entry1_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[1] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[1]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[1],
                                  `LSU_STB.stb_entry1_pa[39:0],
                                  cx_trace_store_bytes_vld[1],
                                  `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_data[63:0]);
        end
        else begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry1_pa[39:0],
                                    `LSU_STB.stb_entry1_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry1_pa[39:0],
                                `LSU_STB.stb_entry1_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_2.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[2]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[2],
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  `LSU_STB.stb_entry2_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[2] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[2]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[2],
                                  `LSU_STB.stb_entry2_pa[39:0],
                                  cx_trace_store_bytes_vld[2],
                                  `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_data[63:0]);
        end
        else begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry2_pa[39:0],
                                    `LSU_STB.stb_entry2_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry2_pa[39:0],
                                `LSU_STB.stb_entry2_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_data[63:0]);
          end
        end
      end
      if(`LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_vld) begin
        if(`LSU_STB.x_aq_lsu_stb_entry_3.stb_entry_amo_inst &&
           cx_trace_amo_pc_vld[3]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_amo_pc[3],
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  `LSU_STB.stb_entry3_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_data[63:0]);
        end
        else if(`LSU_STB.stb_create_en_gate[3] &&
                !`LSU_STB.stb_create_dca_inst &&
                !`LSU_STB.stb_create_amo_inst) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_create_pc(),
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  `LSU_STB.stb_create_bytes_vld[7:0],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_data[63:0]);
        end
        else if(cx_trace_store_pc_vld[3]) begin
          cx_trace_store_with_pc8(cycle_count[31:0],
                                  cx_trace_store_pc[3],
                                  `LSU_STB.stb_entry3_pa[39:0],
                                  cx_trace_store_bytes_vld[3],
                                  `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_data[63:0]);
        end
        else begin
          if(`tb_retire0) begin
            cx_trace_store_with_pc8(cycle_count[31:0],
                                    `retire0_pc,
                                    `LSU_STB.stb_entry3_pa[39:0],
                                    `LSU_STB.stb_entry3_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                    `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_data[63:0]);
          end
          else begin
            cx_trace_store_raw8(cycle_count[31:0],
                                `LSU_STB.stb_entry3_pa[39:0],
                                `LSU_STB.stb_entry3_bytes_vld[7:0] | `LSU_STB.stb_create_bytes_vld[7:0],
                                `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_data[63:0]);
          end
        end
      end
    end
    if(`tb_retire0 || cpu_wvalid ||
       `LSU_STB.stb_create_en_gate[0] || `LSU_STB.stb_create_en_gate[1] ||
       `LSU_STB.stb_create_en_gate[2] || `LSU_STB.stb_create_en_gate[3] ||
       `LSU_STB.x_aq_lsu_stb_entry_0.stb_fwd_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_1.stb_fwd_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_2.stb_fwd_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_3.stb_fwd_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_0.stb_merge_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_1.stb_merge_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_2.stb_merge_vld ||
       `LSU_STB.x_aq_lsu_stb_entry_3.stb_merge_vld ||
       `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb0_vld ||
       `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.rtu_idu_wb1_vld ||
       `CPU_TOP.x_aq_top_0.x_aq_core.vpu_vidu_fp_wb_vld) begin
      $fflush(cx_trace_file);
    end
  end
end
`endif


always @(posedge clk)
begin
  cpu_awlen[3:0]   <= `SOC_TOP.biu_pad_awlen[3:0];
  cpu_awaddr[31:0] <= `SOC_TOP.biu_pad_awaddr[31:0];
  cpu_wvalid       <= `SOC_TOP.biu_pad_wvalid;
  cpu_wstrb        <= `SOC_TOP.biu_pad_wstrb;
  cpu_wdata        <= `SOC_TOP.biu_pad_wdata[127:0];
  value0           <= `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.wb_wb0_data[63:0];
  value1           <= `CPU_TOP.x_aq_top_0.x_aq_core.x_aq_rtu_top.x_aq_rtu_wb.wb_wb1_data[63:0];
end

always @(posedge clk)
begin
  if((value0 == 64'h444333222) || (value1 == 64'h444333222))
  begin
   $display("\n**********************************************");
   $display("*    simulation finished successfully        *");
   $display("**********************************************");
  #10;
   FILE = $fopen("run_case.report","a");
   $fwrite(FILE,"TEST PASS");   
   $fclose(FILE);

   $finish;
  end
  else if ((value0 == 64'h2382348720) || (value1 == 64'h2382348720))
  begin
   $display("**********************************************");
   $display("*    simulation finished with error          *");
   $display("**********************************************");
   #10;
   FILE = $fopen("run_case.report","a");
   $fwrite(FILE,"TEST FAIL");   
   $fclose(FILE);

   $finish;
  end

  else if((cpu_awlen[3:0] == 4'b0) &&
     (cpu_awaddr[31:0] == 32'h10015000) &&
      cpu_wvalid)
  begin
   FILE = $fopen("run_case.report","a");
    if(cpu_wstrb[15:0] == 16'hf) begin
      $write("%c", `SOC_TOP.biu_pad_wdata[7:0]);
      $fwrite(FILE,"%c",`SOC_TOP.biu_pad_wdata[7:0]);
      $fclose(FILE);
   end
   else if(cpu_wstrb[15:0] == 16'hf0) begin
      $write("%c", `SOC_TOP.biu_pad_wdata[39:32]);
      $fwrite(FILE,"%c",`SOC_TOP.biu_pad_wdata[39:32]);
      $fclose(FILE);
   end
   else if(cpu_wstrb[15:0] == 16'hf00) begin
      $write("%c", `SOC_TOP.biu_pad_wdata[71:64]);
      $fwrite(FILE,"%c",`SOC_TOP.biu_pad_wdata[71:64]);
      $fclose(FILE);
   end
   else if(cpu_wstrb[15:0] == 16'hf000) begin
      $write("%c", `SOC_TOP.biu_pad_wdata[103:96]);
      $fwrite(FILE,"%c",`SOC_TOP.biu_pad_wdata[103:96]);
      $fclose(FILE);
   end
  end

end

`ifndef NO_DUMP
initial
begin
`ifdef NC_SIM
  $dumpfile("test.vcd");
  $dumpvars;  
`else
   `ifdef IVERILOG_SIM
     $dumpfile("test.vcd");
     $dumpvars;  
   `else
     $display("######time:%d, Dump start######",$time);
     $fsdbDumpvars();
   `endif
`endif
end
`endif


assign jtg_tdi = 1'b0;
assign jtg_tms = 1'b0;

assign uart0_sin = 1'b1;


soc x_soc(
  .i_pad_clk           ( clk                  ),
  .b_pad_gpio_porta    ( b_pad_gpio_porta     ),
  .i_pad_jtg_trst_b    ( jrst_b               ),
  .i_pad_jtg_nrst_b    ( rst_b                ),
  .i_pad_jtg_tclk      ( jclk                 ),
  .i_pad_jtg_tdi       ( jtg_tdi              ),
  .i_pad_jtg_tms       ( jtg_tms              ),
  .i_pad_uart0_sin     ( uart0_sin            ),
  .o_pad_jtg_tdo       ( jtg_tdo              ),
  .o_pad_uart0_sout    ( uart0_sout           ),
  .i_pad_rst_b         ( rst_b                )
);




endmodule
